version: '3.3'

services:
  traefik:
    image: traefik:v2.9.5
    container_name: 'traefik'
    restart: always
    networks: 
      - traefik
    environment:
      ALICLOUD_ACCESS_KEY: XXXX
      ALICLOUD_SECRET_KEY: XXXX 
      TZ: Asia/Shanghai
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: "Host(`XXX`)"
      traefik.http.routers.traefik.entrypoints: "http, https"
      traefik.http.routers.traefik.middlewares: "redirecthttps@file, basic-auth"
      traefik.http.middlewares.basic-auth.basicauth.users: "XXX"
      traefik.http.routers.traefik.tls: "true"
      traefik.http.routers.traefik.tls.certresolver: "default"
      traefik.http.services.traefik.loadbalancer.server.port: "8080"


    command: 
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.network=traefik"  
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.default.acme.email=891841484@qq.com"
      - "--certificatesresolvers.default.acme.storage=/etc/traefik/acme.json"
      - "--certificatesresolvers.default.acme.dnschallenge=true"
      - "--certificatesresolvers.default.acme.dnschallenge.provider=alidns"
      - "--providers.file.filename=/etc/traefik/traefik-dynamic.yaml"
      - "--providers.file.watch=true"
      - "--log.level=TRACE"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/:/etc/traefik/
networks:
  traefik:
    external: true
